include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    unused_import: error
    unused_local_variable: warning
    dead_code: warning
    deprecated_member_use: info
    use_build_context_synchronously: warning
